backend:
  base_url: https://sveltia-github-auth.marcus-pollio.workers.dev/
  branch: testing
  commit_messages:
    create: '{{collection}}: create {{slug}}'
    delete: '{{collection}}: delete {{slug}}'
    deleteMedia: 'Media: delete {{path}}'
    openAuthoring: '{{message}}'
    update: '{{collection}}: update {{slug}}'
    uploadMedia: 'Media: upload {{path}}'
  name: github
  repo: marcuspollio/FreeCAD-website
collections:
- create: true
  description: This is the News blog collection with FreeCAD articles
  fields:
  - hint: Use a similar title structure as existing articles for coherence
    i18n: true
    label: Article Title
    name: title
    required:
    - en
    widget: string
  - i18n: true
    label: Article Description
    name: description
    widget: string
  - i18n: duplicate
    label: Publication Date
    name: date
    widget: datetime
  - default: FreeCAD
    hint: Use a similar author name as existing ones for coherence
    i18n: duplicate
    label: Article Authors
    name: authors
    pattern:
    - .{3,}
    - Must have at least 3 characters
    widget: string
  - default: true
    i18n: duplicate
    label: Draft
    name: draft
    required: false
    widget: boolean
  - i18n: duplicate
    label: Article Category
    name: categories
    options:
    - announcement
    - event
    - feature
    - showcase
    - tutorial
    - update
    widget: select
  - default: false
    i18n: duplicate
    label: Show Table of Contents
    name: params.ToC
    required: false
    widget: boolean
  - i18n: duplicate
    label: Cover image
    name: cover.image
    widget: image
  - i18n: true
    label: Cover caption
    name: cover.caption
    widget: string
  - i18n: true
    label: Cover alternative text
    name: cover.alt
    widget: string
  - default: false
    hint: Article featured on top of the Homepage
    i18n: duplicate
    label: Hero
    name: params.hero
    required: false
    widget: boolean
  - i18n: true
    label: Content
    linked_images: false
    name: body
    pattern:
    - .{3,}
    - Must have at least 3 characters
    required:
    - en
    widget: markdown
  folder: content/news
  format: frontmatter
  i18n: true
  icon: brand_awareness
  index_file:
    editor:
      preview: true
    fields:
    - i18n: true
      label: Title
      name: title
      pattern:
      - .{3,}
      - Must have at least 3 characters
      required:
      - en
      widget: string
    - i18n: true
      label: Description
      name: description
      widget: string
    - default: 12
      hint: Integer between 1 and 30
      i18n: duplicate
      label: Pagination
      max: 30
      min: 1
      name: paginate
      value_type: int
      widget: number
    - i18n: duplicate
      label: Cover image
      name: cover.image
      widget: image
    - i18n: true
      label: Cover caption
      name: cover.caption
      widget: string
    - i18n: true
      label: Cover alternative text
      name: cover.alt
      widget: string
    icon: brand_awareness
    label: News Index
    name: _index
  label: News
  media_folder: ""
  name: news
  path: '{{year}}/{{month}}/{{slug}}/index'
  public_folder: ""
  slug: '{{slug}}'
  thumbnail: cover.image
- divider: true
- files:
  - fields:
    - i18n: true
      label: Title
      name: title
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: string
    - i18n: true
      label: Description
      name: description
      widget: string
    - default: false
      i18n: duplicate
      label: Show Table of Contents
      name: params.ToC
      required: false
      widget: boolean
    - fields:
      - fields:
        - i18n: true
          label: Label
          name: label
          widget: string
        - i18n: duplicate
          label: URL
          name: url
          widget: string
        i18n: true
        label: Buttons
        name: buttons
        summary: '{{fields.label}}'
        widget: list
      i18n: true
      label: Params
      name: params
      summary: '{{fields.buttons}}'
      widget: object
    - i18n: true
      label: Content
      linked_images: false
      name: body
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: markdown
    file: content/homepage/index.{{locale}}.md
    i18n: true
    icon: home
    label: Homepage
    media_folder: ""
    name: homepage
    public_folder: ""
  format: frontmatter
  i18n: true
  icon: home
  label: Homepage
  name: homepage
- files:
  - fields:
    - i18n: true
      label: Title
      name: title
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: string
    - i18n: true
      label: Description
      name: description
      widget: string
    - default: false
      i18n: duplicate
      label: Show Table of Contents
      name: params.ToC
      required: false
      widget: boolean
    - i18n: duplicate
      label: Cover image
      name: cover.image
      widget: image
    - i18n: true
      label: Cover caption
      name: cover.caption
      widget: string
    - i18n: true
      label: Cover alternative text
      name: cover.alt
      widget: string
    - i18n: true
      label: Content
      linked_images: false
      name: body
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: markdown
    file: content/features/index.{{locale}}.md
    i18n: true
    icon: bolt
    label: Features
    media_folder: ""
    name: features
    public_folder: ""
  format: frontmatter
  i18n: true
  icon: bolt
  label: Features
  name: features
- files:
  - fields:
    - i18n: true
      label: Title
      name: title
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: string
    - i18n: true
      label: Description
      name: description
      widget: string
    - default: false
      i18n: duplicate
      label: Show Table of Contents
      name: params.ToC
      required: false
      widget: boolean
    - i18n: duplicate
      label: Cover image
      name: cover.image
      widget: image
    - i18n: true
      label: Cover caption
      name: cover.caption
      widget: string
    - i18n: true
      label: Cover alternative text
      name: cover.alt
      widget: string
    - i18n: true
      label: Content
      linked_images: false
      name: body
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: markdown
    file: content/download/index.{{locale}}.md
    i18n: true
    icon: downloading
    label: Download
    media_folder: ""
    name: download
    public_folder: ""
  format: frontmatter
  i18n: true
  icon: downloading
  label: Download
  name: download
- create: true
  fields:
  - i18n: true
    label: Release Title
    name: title
    pattern:
    - .{3,}
    - Must have at least 3 characters
    widget: string
  - i18n: true
    label: Release Description
    name: description
    widget: string
  - default: false
    i18n: duplicate
    label: Show Table of Contents
    name: params.ToC
    required: false
    widget: boolean
  - i18n: duplicate
    label: Cover image
    name: cover.image
    widget: image
  - i18n: true
    label: Cover caption
    name: cover.caption
    widget: string
  - i18n: true
    label: Cover alternative text
    name: cover.alt
    widget: string
  - i18n: true
    label: Content
    linked_images: false
    name: body
    pattern:
    - .{3,}
    - Must have at least 3 characters
    widget: markdown
  folder: content/releases
  format: frontmatter
  i18n: true
  icon: celebration
  index_file:
    editor:
      preview: true
    fields:
    - i18n: true
      label: Title
      name: title
      pattern:
      - .{3,}
      - Must have at least 3 characters
      required:
      - en
      widget: string
    - i18n: true
      label: Description
      name: description
      widget: string
    - default: 6
      hint: Integer between 1 and 30
      i18n: duplicate
      label: Pagination
      max: 30
      min: 1
      name: paginate
      value_type: int
      widget: number
    - i18n: duplicate
      label: Cover image
      name: cover.image
      widget: image
    - i18n: true
      label: Cover caption
      name: cover.caption
      widget: string
    - i18n: true
      label: Cover alternative text
      name: cover.alt
      widget: string
    icon: celebration
    label: Releases Index
    name: _index
  label: Releases
  media_folder: ""
  name: releases
  path: '{{slug}}/index'
  public_folder: ""
  slug: '{{slug}}'
  thumbnail: cover.image
- files:
  - fields:
    - i18n: true
      label: Title
      name: title
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: string
    - i18n: true
      label: Description
      name: description
      widget: string
    - default: false
      i18n: duplicate
      label: Show Table of Contents
      name: params.ToC
      required: false
      widget: boolean
    - i18n: duplicate
      label: Cover image
      name: cover.image
      widget: image
    - i18n: true
      label: Cover caption
      name: cover.caption
      widget: string
    - i18n: true
      label: Cover alternative text
      name: cover.alt
      widget: string
    - i18n: true
      label: Content
      linked_images: false
      name: body
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: markdown
    file: content/community/index.{{locale}}.md
    i18n: true
    icon: hub
    label: Community
    media_folder: ""
    name: community
    public_folder: ""
  format: frontmatter
  i18n: true
  icon: hub
  label: Community
  name: community
- files:
  - fields:
    - i18n: true
      label: Title
      name: title
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: string
    - i18n: true
      label: Description
      name: description
      widget: string
    - default: false
      i18n: duplicate
      label: Show Table of Contents
      name: params.ToC
      required: false
      widget: boolean
    - i18n: duplicate
      label: Cover image
      name: cover.image
      widget: image
    - i18n: true
      label: Cover caption
      name: cover.caption
      widget: string
    - i18n: true
      label: Cover alternative text
      name: cover.alt
      widget: string
    - i18n: true
      label: Content
      linked_images: false
      name: body
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: markdown
    file: content/documentation/index.{{locale}}.md
    i18n: true
    icon: local_library
    label: Documentation
    media_folder: ""
    name: documentation
    public_folder: ""
  format: frontmatter
  i18n: true
  icon: local_library
  label: Documentation
  name: documentation
- files:
  - fields:
    - i18n: true
      label: Title
      name: title
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: string
    - i18n: true
      label: Description
      name: description
      widget: string
    - default: false
      i18n: duplicate
      label: Show Table of Contents
      name: params.ToC
      required: false
      widget: boolean
    - i18n: duplicate
      label: Cover image
      name: cover.image
      widget: image
    - i18n: true
      label: Cover caption
      name: cover.caption
      widget: string
    - i18n: true
      label: Cover alternative text
      name: cover.alt
      widget: string
    - i18n: true
      label: Content
      linked_images: false
      name: body
      pattern:
      - .{3,}
      - Must have at least 3 characters
      widget: markdown
    file: content/contribute/index.{{locale}}.md
    i18n: true
    icon: code_blocks
    label: Contribute
    media_folder: ""
    name: contribute
    public_folder: ""
  format: frontmatter
  i18n: true
  icon: code_blocks
  label: Contribute
  name: contribute
  slug: '{{slug}}'
- fields:
  - label: Donate Page Title
    name: title
    pattern:
    - .{3,}
    - Must have at least 3 characters
    widget: string
  - label: Donate Page Description
    name: description
    widget: string
  - i18n: duplicate
    label: Cover image
    name: cover.image
    widget: image
  - i18n: true
    label: Cover caption
    name: cover.caption
    widget: string
  - i18n: true
    label: Cover alternative text
    name: cover.alt
    widget: string
  - label: Content
    linked_images: false
    name: body
    pattern:
    - .{3,}
    - Must have at least 3 characters
    widget: markdown
  folder: content/donate
  format: frontmatter
  i18n: true
  icon: volunteer_activism
  label: Donate
  media_folder: ""
  name: donate
  path: '{{slug}}/index'
  public_folder: ""
  slug: '{{slug}}'
  thumbnail: cover.image
i18n:
  default_locale: en
  initial_locales: default
  locales:
  - en
  - fr
  - tr
  structure: multiple_files
locale: es-ES
logo_url: https://marcuspollio.github.io/FreeCAD-website/FreeCAD-symbol.svg
media_folder: static
media_libraries:
  default:
    config:
      max_file_size: 2048000
      slugify_filename: true
      transformations:
        raster_image:
          format: webp
          height: 2000
          quality: 90
          width: 2000
        svg:
          optimize: true
public_folder: /
singletons:
- fields:
  - fields:
    - label: Title
      name: title
      widget: string
    - label: URL
      name: url
      widget: string
    - label: Parent
      name: parent
      options:
      - features
      - download
      - releases
      - news
      - community
      - documentation
      - contribute
      - donate
      required: false
      widget: select
    label: Footer links
    name: footer
    root: true
    widget: list
  file: themes/Trigo/data/footer.yaml
  icon: bottom_navigation
  label: Footer
  name: footer
- fields:
  - allow_add: false
    fields:
    - i18n: duplicate
      label: String ID
      name: id
      widget: string
    - i18n: true
      label: Translation
      name: translation
      required: false
      widget: string
    i18n: true
    label: Theme i18n strings
    name: i18n
    root: true
    summary: '{{fields.id}}'
    widget: list
  file: themes/Trigo/i18n/{{locale}}.yaml
  i18n: true
  icon: translate
  label: Theme strings translations
  name: theme
site_url: https://marcuspollio.github.io/FreeCAD-website/
slug:
  clean_accents: true
  encoding: ascii
  sanitize_replacement: '-'
